validate release actions support mulit os (#197)
* add validate-release.sh

---------

Co-authored-by: imbajin <jin@apache.org>

diff --git a/.github/workflows/validate-release.yml b/.github/workflows/validate-release.yml
--- a/.github/workflows/validate-release.yml
+++ b/.github/workflows/validate-release.yml
@@ -6,6 +6,9 @@ on:
       release_version:
         required: true
         default: '1.0.0'
+      gpg_user:
+        required: true
+        default: 'imbajin'
 
   push:
     branches:
@@ -16,11 +19,12 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    name: "Build On ${{ matrix.os }} (java-${{ matrix.java_version }})"
+    runs-on: ${{ matrix.os }}
     env:
       SCRIPT_PATH: hugegraph-dist/scripts/
       URL_PREFIX: https://dist.apache.org/repos/dist/dev/incubator/hugegraph/
-      USER: 'imbajin'
+      USER: ${{ inputs.gpg_user }}
       # TODO: parse version from the running branch name & also adapt the input version
       RELEASE_VERSION: ''
     steps:
@@ -89,7 +93,7 @@ jobs:
             echo "$i"
             # 4.0 check the directory name include "incubating"
             if [[ ! "$i" =~ "incubating" ]]; then
-              echo "The package name should include incubating" && exit 1
+              echo "The package name $i should include incubating" && exit 1
             fi
             tar xzvf "$i" || exit
             cd "$(basename "$i" .tar.gz)" || exit
@@ -104,32 +108,41 @@ jobs:
             if [[ ! -f "DISCLAIMER" ]]; then
                 echo "The package should include DISCLAIMER file" && exit 1
             fi
+            # 4.2 ensure doesn't contains *GPL/BCL/JSR-275/RSAL/QPL/SSPL/CPOL/NPL1.*/CC-BY 
+            #     dependency in LICENSE and NOTICE file 
+            COUNT=$(grep -E "GPL|BCL|JSR-275|RSAL|QPL|SSPL|CPOL|NPL1|CC-BY" LICENSE NOTICE | wc -l)
+            if [[ $COUNT -ne 0 ]]; then
+              grep -E "GPL|BCL|JSR-275|RSAL|QPL|SSPL|CPOL|NPL1.0|CC-BY" LICENSE NOTICE
+              echo "The package shouldn't include GPL* invalid dependency, but get $COUNT" && exit 1
+            fi
 
-            # 4.2 ensure doesn't contains empty directory or file
+            # 4.3 ensure doesn't contains empty directory or file
             COUNT=$(find . -type d -empty | wc -l)
             if [[ $COUNT -ne 0 ]]; then
               find . -type d -empty
-              echo "The package shouldn't include empty directory, but get $COUNT" # TODO: && exit 1
+              echo "The package shouldn't include empty directory, but get $COUNT" && exit 1
             fi
           
-            # 4.3 ensure any file should less than 900kb & not include binary file
+            # 4.4 ensure any file should less than 900kb & not include binary file
             COUNT=$(find . -type f -size +900k | wc -l)
             if [[ $COUNT -ne 0 ]]; then
               find . -type f -size +900k
-              echo "The package shouldn't include file larger than 900kb, but get $COUNT"
+              echo "The package shouldn't include file larger than 900kb, but get $COUNT" && exit 1
             fi
-            COUNT=$(find . -type f | perl -lne 'print if -B' | grep -v *.txt | wc -l)
+            COUNT=$(find . -type f | grep -v .txt | perl -lne 'print if -B' | wc -l)
             if [[ $COUNT -ne 0 ]]; then
-              find . -type f | perl -lne 'print if -B'
-              echo "The package shouldn't include binary file, but get $COUNT"
+              find . -type f | grep -v .txt | perl -lne 'print if -B'
+              # due to the search script is not perfect, we can't exit here (check manually)
+              echo "The package shouldn't include binary file, but get $COUNT" && exit 1
             fi
           
-            # 4.4 test compile the packages
-            if [[ $JAVA_VERSION == 8 && "$i" =~ "computer" ]]; then
+            # 4.5 test compile the packages
+            if [[ ${{ matrix.java_version }} == 8 && "$i" =~ "computer" ]]; then
               cd .. && echo "skip computer module in java8"
               continue
             fi
-            mvn package -DskipTests -ntp && ls -lh
+            mvn package -DskipTests -ntp -e || exit 1
+            ls -lh
             cd .. || exit
           done
 
@@ -168,6 +181,8 @@ jobs:
           echo "test hubble"
           cd ./*hubble*${{ inputs.release_version }} || exit
           cat conf/hugegraph-hubble.properties && bin/start-hubble.sh
+          # TODO: need stop the server here
+          jps | grep HugeGraphServer | awk '{print $1}' | xargs kill -9
           cd ../../../ || exit
           rm -rf ./*src* && ls -lh
 
@@ -178,14 +193,15 @@ jobs:
             echo "$i"
             # 7.0 check the directory name include "incubating"
             if [[ ! "$i" =~ "incubating" ]]; then
-              echo "The package name should include incubating" && exit 1
+              echo "The package name $i should include incubating" && exit 1
             fi
             tar xzvf "$i" || exit
 
-            # 7.1 check root dir include "NOTICE"/"LICENSE"/"DISCLAIMER" files & "release-docs" dir
-            cd "$(basename "$i" .tar.gz)" && ls -lh || exit
+            # 7.1 check root dir include "NOTICE"/"LICENSE"/"DISCLAIMER" & "licenses" dir
+            cd "$(basename "$i" .tar.gz)" || exit
+            ls -lh
             if [[ ! -f "LICENSE" ]]; then
-              echo "The package should include LICENSE file" && exit 1
+              echo "The package should include LICENSE file" && ls -lh && exit 1
             fi
             if [[ ! -f "NOTICE" ]]; then
               echo "The package should include NOTICE file" && exit 1
@@ -193,15 +209,23 @@ jobs:
             if [[ ! -f "DISCLAIMER" ]]; then
                 echo "The package should include DISCLAIMER file" && exit 1
             fi
-            if [[ ! -d "release-docs" ]]; then
-              echo "The package should include release-docs dir" && exit 1
+            if [[ ! -d "licenses" ]]; then
+              echo "The package should include licenses dir" && exit 1
+            fi
+
+            # 7.2 ensure doesn't contains *GPL/BCL/JSR-275/RSAL/QPL/SSPL/CPOL/NPL1.*/CC-BY 
+            #     dependency in LICENSE/NOTICE and licenses/* files 
+            COUNT=$(grep -r -E "GPL|BCL|JSR-275|RSAL|QPL|SSPL|CPOL|NPL1|CC-BY" LICENSE NOTICE licenses | wc -l)
+            if [[ $COUNT -ne 0 ]]; then
+              grep -r -E "GPL|BCL|JSR-275|RSAL|QPL|SSPL|CPQL|NPL1|CC-BY" LICENSE NOTICE licenses
+              echo "The package shouldn't include GPL* invalid dependency, but get $COUNT" && exit 1
             fi
           
-            # 7.2 ensure doesn't contains empty directory or file
+            # 7.3 ensure doesn't contains empty directory or file
             COUNT=$(find . -type d -empty | wc -l)
             if [[ $COUNT -ne 0 ]]; then
               find . -type d -empty
-              echo "The package shouldn't include empty directory, but get $COUNT" # TODO: && exit 1
+              echo "The package shouldn't include empty directory, but get $COUNT" && exit 1
             fi
 
             cd - || exit
@@ -212,8 +236,6 @@ jobs:
           cd dist/${{ inputs.release_version }}
           cd ./*hugegraph-incubating*${{ inputs.release_version }} || exit
           bin/init-store.sh && sleep 1
-          # kill the HugeGraphServer process by jps
-          jps | grep HugeGraphServer | awk '{print $1}' | xargs kill -9
           bin/start-hugegraph.sh && ls ../
           cd - || exit
 
@@ -245,8 +267,12 @@ jobs:
           cat conf/hugegraph-hubble.properties
           bin/stop-hubble.sh && bin/start-hubble.sh
           cd - || exit
+          # TODO: need stop the server here 
+          jps | grep HugeGraphServer | awk '{print $1}' | xargs kill -9
 
     strategy:
       fail-fast: false
       matrix:
         java_version: [ '8','11' ]
+        # TODO: support windows-latest or other OS in future
+        os: [ubuntu-latest, macos-latest]
